import libs = \
  libsfml-graphics%lib{sfml-graphics} \
  glbinding%lib{glbinding} \
  glm%lib{glm} \
  assimp%lib{assimp}

define glsl: file
glsl{*}: extension = glsl

exe{exaggerated-shading-demo}: {hxx ixx txx cxx glsl}{**} $libs
{
  # test.arguments = /home/lyrahgames/projects/sgp2024/data/gargoyle.obj
  test.arguments = /home/lyrahgames/projects/sgp2024/data/armadillo/armadillo.obj
  # test.arguments = /home/lyrahgames/projects/sgp2024/data/memento.obj
}

cxx.poptions =+ "-I$out_root" "-I$src_root"
