import libs = \
  libsfml-graphics%lib{sfml-graphics} \
  glbinding%lib{glbinding} \
  glm%lib{glm}

exe{exaggerated-shading-demo}: {hxx ixx txx cxx}{**} $libs
{
  test.arguments = /home/lyrahgames/Downloads/Thingi10K/raw_meshes/100026.stl
}

cxx.poptions =+ "-I$out_root" "-I$src_root"
