import libs = \
  libsfml-graphics%lib{sfml-graphics} \
  glbinding%lib{glbinding} \
  glm%lib{glm}

define glsl: file
glsl{*}: extension = glsl

exe{exaggerated-shading-demo}: {hxx ixx txx cxx glsl}{**} $libs
{
  test.arguments = /home/lyrahgames/data/models/blender-suzanne.stl
}

cxx.poptions =+ "-I$out_root" "-I$src_root"
